name: TEST
on:
  push:
    branches: [ actionsTest ]
jobs:
  publish: 
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.TEST_HOST }}
            username: ${{ secrets.TEST_USERNAME }}
            key: ${{ secrets.TEST_SSH_KEY }}
            script: |
              whoami
              ls -al