name: TEST
on:
  push:
    branches: [ actionsTest ]
env:
  TRIGGERED_BRANCH: ${{ github.ref }}
  BUILD_SCRIPT: |
              whoami
              cd /var/www/browser-timer
              pwd
              git branch
              echo ${{ github.ref }}
              echo ${{ github.ref == 'refs/heads/actionsTest' }}

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: dev deploy
        uses: appleboy/ssh-action@master
        if: ${{ env.TRIGGERED_BRANCH == 'refs/heads/actionsTest' }}
        with:
            host: ${{ secrets.TEST_HOST }}
            username: ${{ secrets.TEST_USERNAME }}
            key: ${{ secrets.TEST_SSH_KEY }}
            script: | 
              ${{ env.BUILD_SCRIPT }}
              pwd
              ll
              echo man~ github actions man~