name: Npm_publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish: 
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
