name: TEST
on:
  push:
    branches: [ actionsTest ]
env:
  TRIGGERED_BRANCH: ${{ github.ref == 'refs/heads/main' && 'main' || github.ref == 'refs/heads/actionsTest' && 'actionsTest'}}
jobs:
  deploy:
      
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      - name: dev deploy
        uses: appleboy/ssh-action@master
        if: ${{ env.TRIGGERED_BRANCH == 'actionsTest' }}
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          script: |
            cd /var/www/browser-timer
            pwd

      - name: main deploy
        uses: appleboy/ssh-action@master
        if: ${{ env.TRIGGERED_BRANCH == 'main' }}
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          script: | 
            ${{ env.PRE_BUILD_SCRIPT }}
            npm run dev-build