name: TEST
on:
  push:
    branches: [ actionsTest ]
env:
  BUILD_SCRIPT: |
              whoami
              cd /var/www/browser-timer
              pwd
              git branch
              echo ${{ github.head_ref }}

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: dev deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.TEST_HOST }}
            username: ${{ secrets.TEST_USERNAME }}
            key: ${{ secrets.TEST_SSH_KEY }}
            script: ${{ env.BUILD_SCRIPT }}